FROM ubuntu:latest

# Abrindo a porta 67 para o DHCP
RUN apt-get update && apt-get install -y isc-dhcp-client
RUN apt install net-tools -y

RUN mkdir -p /var/lib/dhcp/ && \
    touch /var/lib/dhcp/dhcpd.leases && \
    chmod 666 /var/lib/dhcp/dhcpd.leases

# Configurar o servidor DHCP
COPY ./dhcpd.conf /etc/dhcp/dhcpd.conf

EXPOSE 67/udp

# Comando para iniciar o DHCP
CMD ["dhcpd", "-f", "-d", "--no-pid"]


