FROM ubuntu:latest

# Instalando o cliente DHCP e o utilitário net-tools (para o comando ifconfig) e iputils-ping (para o comando ping) e dnsutils (para o comando nslookup)
RUN apt-get update && apt-get install -y isc-dhcp-client
RUN apt install net-tools -y
RUN apt install iputils-ping -y
RUN apt install dnsutils -y

# Fazendo uma requisição de IP para o servidor DHCP (eth0 é a interface de rede do container)
CMD [ "dhclient", "-v", "eth0"]
